alphabet = 'abcdefg'
print("Нам дан набор букв: ", alphabet)
print('Результат: ')
print(alphabet[::-1])
print(alphabet[::2])
print(alphabet[1::2])
print(alphabet[:1])
print(alphabet[-1:])
print(alphabet[3:4])
print(alphabet[-3:])
print(alphabet[3:5])
print(alphabet[3:5][::-1])
